spring:
  profiles:
    active: dev1

management:
  health:
    db:
      enabled: false
    mail:
      enabled: false
    redis:
      enabled: false
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有节点 "bus-refresh"
      health:
        senysssitive: false #关闭过滤敏感信息
  endpoint:
    health:
      show-details: ALWAYS  #显示详细信息
    shutdown:
      enabled: true

---
server:
  port: 8000
spring:
  profiles: dev1
  application:
    name: scheduler-zhangwei
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8 #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8  #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0 #最小等待连接中的数量,设 0 为没有限制
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 1000ms
microservice:
  scheduler:
    cluster-address: 192.168.40.1:9991;192.168.40.1:9992
    #    server-address: 192.168.40.1:9991
    register-name: ${spring.application.name}-01
    server-port: 9991

---
server:
  port: 8001
spring:
  profiles: dev2
  application:
    name: scheduler-zhangwei
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8 #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8  #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0 #最小等待连接中的数量,设 0 为没有限制
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 1000ms
microservice:
  scheduler:
    cluster-address: 192.168.40.1:9991;192.168.40.1:9992
    register-name: ${spring.application.name}-02
    server-port: 9992